//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int PNo { get; set; }
        public Nullable<int> CustNo { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> ShipDate { get; set; }
        public string ToCity { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
